In [11]:
class Student:
    def __init__(self):
        print('냠냠')

In [12]:
gh = Student() # 독립적인 값을 보장하는 인스턴스로 생성
gh.eat_food()

냠냠


In [17]:
class Person:
    def __init__(self):
        self.hello = "안녕하세요"

In [18]:
james = Person()
james.hello

'안녕하세요'

In [20]:
bebe = Person()
bebe.hello

'안녕하세요'

In [18]:
set_variable = set()
print(set_variable, type(set_variable))

set() <class 'set'>


In [19]:
A = {_ for _ in range(1,5)}
B = {_ for _ in range(2,6) if _ != 3}

In [25]:
class Student:
    def __init__(self):
        self.hello = '안녕하세요'
    def greeting(self):
        print(self.hello)

In [26]:
stu_a = Student()
stu_b = Student()

In [30]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        

In [31]:
stu_a = Person('sangwook', 35)

In [34]:
stu_a.age

35

In [52]:
class Person2:
    def __init__(self, name, age, adress):
        self.hello = '안녕하세요'
        self.name = name
        self.age = age
        self.adress = adress
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')
        
maria = Person2('마리아', 23, '서울시 마포구')
maria.greeting()
print(maria.__dict__)
print(maria.name)
print(maria.name)
print(maria.name)


안녕하세요 제 이름은 마리아입니다.
{'hello': '안녕하세요', 'name': '마리아', 'age': 23, 'adress': '서울시 마포구'}


In [49]:
maria.greeting()

안녕하세요 제 이름은 마리아입니다.


In [66]:
class Person:
    def __init__(self, name, age, adress):
        self.name = name
        self.age = age
        self.adress = adress
        
a = Person(input('이름은 무엇인가요?'), input('나이는 무엇인가요?'), input('주소는 무엇인가요?'))
b = Person(input('이름은 무엇인가요?'), input('나이는 무엇인가요?'), input('주소는 무엇인가요?'))

print(f"첫번째 이름 : {a.name}")
print(f"첫번째 나이 : {a.age}")
print(f"첫번째 주소 : {a.adress}")
print(f"두번째 이름 : {b.name}")
print(f"두번째 나이 : {b.age}")
print(f"두번째 주소 : {b.adress}")


1 name ㅇ
2 age ㅇ
3 adress ㅇ
첫번째 이름 : ㅇ
첫번째 나이 : ㅇ
첫번째 주소 : ㅇ
두번째 이름 : ㅇ
두번째 나이 : ㅇ
두번째 주소 : ㅇ


In [59]:
a.__dict__
b.__dict__

{'name': '제임스', 'age': '21', 'adress': '서울시 구로구'}

In [ ]:
class ClassName:
    def __init__(self, param1, param2):
        self.attr1 = param1
        self.__attr2 = param2 # 비공개 속성

In [87]:
class Person3:
    org = 'abcdefg'
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)
        
    def pay(self, amount):
        if self.__wallet < amount:
            print('돈이 모자랍니다.')
            return
        self.__wallet -= amount
    
    @staticmethod
    # 객체와 상관없이 동작하는 메서드, class, self 둘 다 안씀
    def pay(amount):
        pass
    
    @classmethod
    # 클래스 자체에 동작하는 메서드(self 안씀)
    def from_string(cls, string):
        name, age , address, __wallet = string.split(',')
        return cls(name, age, address, __wallet) # cls는 클래스의 줄임말
    
    

In [ ]:
Person3.org = 

In [75]:
iks = Person3("이기수", 88, "경기도 시흥", 20000)

In [80]:
iks.pay(2000)

In [81]:
iks.amount()

5000


In [86]:
class Character:
    def __init__(self, hp, mp, ap):
        self.hp = hp
        self.mp = mp
        self.ap = ap
    def tibbers(self):
        return self.ap * 0.65 + 400
    
hp, mp, ap = map(float, input('체력, 마나, AP를 입력하세요').split())
annie = Character(hp, mp, ap)
print(f'티버: 피해량 {annie.tibbers()}')

ValueError: not enough values to unpack (expected 3, got 1)

In [97]:
import numpy as np
arr = [1,2,3,5,3,23,]
ar = np.array([_ for _ in arr])

# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료 중 제일 큰 값이 <U5지만 <U8로 타입이 지정 되었다.
ar5 = np.array(['가나다리바사', '바사아' ,'자',' 차카'], 'U8')

In [99]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2 * a + b)
# array([12,24,36])
print(a == 2)
# array([False, True, False])
print(b > 10)
# array([False, True, True])
print((a == 2) & (b > 10))
# array([False, True, False))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [113]:
c = np.array([[1,2,3],[4,5,6]]) # 2 x 3 array
print(c.shape)
print(c)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [114]:
len(c[0])

3

In [116]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [119]:
np.array([_ for _ in range(8)]).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [135]:

m = np.array([_ for _ in range(15)]).reshape(3,5)
print(m)
print(m[1,2])
print(m[2,4])
print(m[1,1:3])
print(m[1:3, 2])
print(m[0:2, 3:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
14
[6 7]
[ 7 12]


array([[3, 4],
       [8, 9]])

In [137]:
ex = np.linspace(0, 100, 20)
ex

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [149]:
array1 = np.zeros(9).reshape(3,3)
array2 = np.ones(6).reshape(3,2)
zeroone = np.hstack((array1, array2))
array4 = np.array([_ for _ in range(10, 151, 10)]).reshape(3,5)
np.vstack((zeroone,array4,zeroone,array4))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [88]:
import numpy as np
class Calculator:
    def __init__(self):
        self.value = 0
    def add(self, *args):
        if len(args) == 0:
            print('숫자를 입력해주세요')
        else:
            self.value += np.sum(args)
        
    def minus(self, *args):
        if len(args) == 0:
            print('숫자를 입력해주세요')
        else:
            self.value -= np.sum(args)
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')
    

In [89]:
c = Calculator()

In [105]:
c.add(100)

In [107]:
c.show_value()

현재 값은 345입니다.


In [91]:
c.minus(20)

(20,)


In [92]:
c.show_value()

현재 값은 80입니다.


In [93]:
c.add()

숫자를 입력해주세요


In [94]:
c.minus(20, 30)

(20, 30)


In [95]:
c.show_value()

현재 값은 30입니다.


In [96]:
c.add([70,80])

In [97]:
c.show_value()

현재 값은 180입니다.


In [98]:
c.add(50)

In [99]:
c.show_value()

현재 값은 230입니다.


In [102]:
c.add(range(1,6))

In [103]:
c.show_value()

현재 값은 245입니다.


In [108]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [116]:
print(practice.max())
print(practice.sum(axis = 0))
print(practice.max(axis = 0))
print(practice.mean(axis = 1))
print(practice.min(axis = 1))

array([0.7, 1.1, 2.7, 2.1, 2.8, 0.2])

In [117]:
import pandas as pd
pd.DataFrame(practice)

0    1    2    3    4    5
0  1.1  7.1  8.0  2.1  6.5  7.2
1  2.7  5.2  3.3  9.0  7.7  2.8
2  0.7  8.8  4.2  8.9  4.3  7.4
3  8.2  1.1  5.4  2.9  6.9  0.2
4  7.4  4.8  2.7  3.1  2.8  8.9

In [130]:
a = np.array([4,3,5,7])



In [132]:
# 정렬이 아니라 순서만
a[np.argsort(a)]


array([3, 4, 5, 7])

In [134]:
scores = np.array([[1,2,3,4],
                  [46,99,100,71],
                  [81, 59, 90, 100]])

In [152]:
scores[:, np.argsort(scores)[1]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [148]:
scores

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [153]:
a = '321'
a[1] = '1'

TypeError: 'str' object does not support item assignment

In [179]:
np.random.seed(0)
print(f'{sum(np.random.binomial(n = 1000, p = 0.5) == 1)/100}')

TypeError: 'bool' object is not iterable

In [13]:
import numpy as np
size = 100
np.random.seed(0)
print(f'{sum(np.random.binomial(n = 1, p = 0.5, size = size)) / size * 100}%')

49.0%


In [25]:
np.random.seed(0)
sum((np.random.randint(1,6) for x in range(100))) / 100

2.96

In [28]:
np.random.seed(0)
size = 100
np.random.randint(1,6, size).sum() / size

2.96